/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.bts.parser.antlr.internal.InternalBTSParser;
import org.xtext.example.bts.services.BTSGrammarAccess;

public class BTSParser extends AbstractAntlrParser {

	@Inject
	private BTSGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBTSParser createParser(XtextTokenStream stream) {
		return new InternalBTSParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "BTS";
	}

	public BTSGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BTSGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
