/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.bts.BTSRuntimeModule;
import org.xtext.example.bts.BTSStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class BTSIdeSetup extends BTSStandaloneSetup {
  @Override
  public Injector createInjector() {
    BTSRuntimeModule _bTSRuntimeModule = new BTSRuntimeModule();
    BTSIdeModule _bTSIdeModule = new BTSIdeModule();
    return Guice.createInjector(Modules2.mixin(_bTSRuntimeModule, _bTSIdeModule));
  }
}
