/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BTSIdeModule extends AbstractBTSIdeModule {
}
