/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBTSScopeProvider extends DelegatingScopeProvider {
}
