/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.bts.BTSRuntimeModule
import org.xtext.example.bts.BTSStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BTSIdeSetup extends BTSStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BTSRuntimeModule, new BTSIdeModule))
	}
	
}
