/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BTSRuntimeModule extends AbstractBTSRuntimeModule {
}
