/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BTSStandaloneSetup extends BTSStandaloneSetupGenerated {

	def static void doSetup() {
		new BTSStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
