/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts.bTS;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Baggage</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.bts.bTS.BTSPackage#getBaggage()
 * @model
 * @generated
 */
public interface Baggage extends Type
{
} // Baggage
