/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts.bTS;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.bts.bTS.BTSFactory
 * @model kind="package"
 * @generated
 */
public interface BTSPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "bTS";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/bts/BTS";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "bTS";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BTSPackage eINSTANCE = org.xtext.example.bts.bTS.impl.BTSPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.bts.bTS.impl.BTSImpl <em>BTS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bts.bTS.impl.BTSImpl
   * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getBTS()
   * @generated
   */
  int BTS = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BTS__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>BTS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bts.bTS.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bts.bTS.impl.TypeImpl
   * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bts.bTS.impl.BaggageImpl <em>Baggage</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bts.bTS.impl.BaggageImpl
   * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getBaggage()
   * @generated
   */
  int BAGGAGE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BAGGAGE__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Baggage</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BAGGAGE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bts.bTS.impl.BookingImpl <em>Booking</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bts.bTS.impl.BookingImpl
   * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getBooking()
   * @generated
   */
  int BOOKING = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOKING__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Booking</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOKING_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bts.bTS.impl.TicketImpl <em>Ticket</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bts.bTS.impl.TicketImpl
   * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getTicket()
   * @generated
   */
  int TICKET = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TICKET__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Ticket</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TICKET_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bts.bTS.impl.PassengerImpl <em>Passenger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bts.bTS.impl.PassengerImpl
   * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getPassenger()
   * @generated
   */
  int PASSENGER = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSENGER__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Passenger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSENGER_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bts.bTS.impl.PaymentImpl <em>Payment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bts.bTS.impl.PaymentImpl
   * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getPayment()
   * @generated
   */
  int PAYMENT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Payment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bts.bTS.impl.OnlinePaymentImpl <em>Online Payment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bts.bTS.impl.OnlinePaymentImpl
   * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getOnlinePayment()
   * @generated
   */
  int ONLINE_PAYMENT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONLINE_PAYMENT__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONLINE_PAYMENT__SUPER_TYPE = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Online Payment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONLINE_PAYMENT_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bts.bTS.impl.KIOSKImpl <em>KIOSK</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bts.bTS.impl.KIOSKImpl
   * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getKIOSK()
   * @generated
   */
  int KIOSK = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KIOSK__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KIOSK__SUPER_TYPE = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>KIOSK</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KIOSK_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bts.bTS.impl.BusImpl <em>Bus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bts.bTS.impl.BusImpl
   * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getBus()
   * @generated
   */
  int BUS = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUS__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Bus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUS_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bts.bTS.impl.CityImpl <em>City</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bts.bTS.impl.CityImpl
   * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getCity()
   * @generated
   */
  int CITY = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CITY__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Busstops</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CITY__BUSSTOPS = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>City</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CITY_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bts.bTS.impl.SeatImpl <em>Seat</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bts.bTS.impl.SeatImpl
   * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getSeat()
   * @generated
   */
  int SEAT = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEAT__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Seat</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEAT_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bts.bTS.Point <em>Point</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bts.bTS.Point
   * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getPoint()
   * @generated
   */
  int POINT = 12;


  /**
   * Returns the meta object for class '{@link org.xtext.example.bts.bTS.BTS <em>BTS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BTS</em>'.
   * @see org.xtext.example.bts.bTS.BTS
   * @generated
   */
  EClass getBTS();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bts.bTS.BTS#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.bts.bTS.BTS#getElements()
   * @see #getBTS()
   * @generated
   */
  EReference getBTS_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bts.bTS.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.example.bts.bTS.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bts.bTS.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.bts.bTS.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bts.bTS.Baggage <em>Baggage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Baggage</em>'.
   * @see org.xtext.example.bts.bTS.Baggage
   * @generated
   */
  EClass getBaggage();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bts.bTS.Booking <em>Booking</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Booking</em>'.
   * @see org.xtext.example.bts.bTS.Booking
   * @generated
   */
  EClass getBooking();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bts.bTS.Ticket <em>Ticket</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ticket</em>'.
   * @see org.xtext.example.bts.bTS.Ticket
   * @generated
   */
  EClass getTicket();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bts.bTS.Passenger <em>Passenger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Passenger</em>'.
   * @see org.xtext.example.bts.bTS.Passenger
   * @generated
   */
  EClass getPassenger();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bts.bTS.Payment <em>Payment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Payment</em>'.
   * @see org.xtext.example.bts.bTS.Payment
   * @generated
   */
  EClass getPayment();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bts.bTS.OnlinePayment <em>Online Payment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Online Payment</em>'.
   * @see org.xtext.example.bts.bTS.OnlinePayment
   * @generated
   */
  EClass getOnlinePayment();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.bts.bTS.OnlinePayment#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see org.xtext.example.bts.bTS.OnlinePayment#getSuperType()
   * @see #getOnlinePayment()
   * @generated
   */
  EReference getOnlinePayment_SuperType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bts.bTS.KIOSK <em>KIOSK</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>KIOSK</em>'.
   * @see org.xtext.example.bts.bTS.KIOSK
   * @generated
   */
  EClass getKIOSK();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.bts.bTS.KIOSK#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see org.xtext.example.bts.bTS.KIOSK#getSuperType()
   * @see #getKIOSK()
   * @generated
   */
  EReference getKIOSK_SuperType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bts.bTS.Bus <em>Bus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bus</em>'.
   * @see org.xtext.example.bts.bTS.Bus
   * @generated
   */
  EClass getBus();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bts.bTS.City <em>City</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>City</em>'.
   * @see org.xtext.example.bts.bTS.City
   * @generated
   */
  EClass getCity();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.bts.bTS.City#getBusstops <em>Busstops</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Busstops</em>'.
   * @see org.xtext.example.bts.bTS.City#getBusstops()
   * @see #getCity()
   * @generated
   */
  EAttribute getCity_Busstops();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bts.bTS.Seat <em>Seat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Seat</em>'.
   * @see org.xtext.example.bts.bTS.Seat
   * @generated
   */
  EClass getSeat();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.bts.bTS.Point <em>Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Point</em>'.
   * @see org.xtext.example.bts.bTS.Point
   * @generated
   */
  EEnum getPoint();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BTSFactory getBTSFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.bts.bTS.impl.BTSImpl <em>BTS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bts.bTS.impl.BTSImpl
     * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getBTS()
     * @generated
     */
    EClass BTS = eINSTANCE.getBTS();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BTS__ELEMENTS = eINSTANCE.getBTS_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.bts.bTS.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bts.bTS.impl.TypeImpl
     * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.bts.bTS.impl.BaggageImpl <em>Baggage</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bts.bTS.impl.BaggageImpl
     * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getBaggage()
     * @generated
     */
    EClass BAGGAGE = eINSTANCE.getBaggage();

    /**
     * The meta object literal for the '{@link org.xtext.example.bts.bTS.impl.BookingImpl <em>Booking</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bts.bTS.impl.BookingImpl
     * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getBooking()
     * @generated
     */
    EClass BOOKING = eINSTANCE.getBooking();

    /**
     * The meta object literal for the '{@link org.xtext.example.bts.bTS.impl.TicketImpl <em>Ticket</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bts.bTS.impl.TicketImpl
     * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getTicket()
     * @generated
     */
    EClass TICKET = eINSTANCE.getTicket();

    /**
     * The meta object literal for the '{@link org.xtext.example.bts.bTS.impl.PassengerImpl <em>Passenger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bts.bTS.impl.PassengerImpl
     * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getPassenger()
     * @generated
     */
    EClass PASSENGER = eINSTANCE.getPassenger();

    /**
     * The meta object literal for the '{@link org.xtext.example.bts.bTS.impl.PaymentImpl <em>Payment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bts.bTS.impl.PaymentImpl
     * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getPayment()
     * @generated
     */
    EClass PAYMENT = eINSTANCE.getPayment();

    /**
     * The meta object literal for the '{@link org.xtext.example.bts.bTS.impl.OnlinePaymentImpl <em>Online Payment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bts.bTS.impl.OnlinePaymentImpl
     * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getOnlinePayment()
     * @generated
     */
    EClass ONLINE_PAYMENT = eINSTANCE.getOnlinePayment();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ONLINE_PAYMENT__SUPER_TYPE = eINSTANCE.getOnlinePayment_SuperType();

    /**
     * The meta object literal for the '{@link org.xtext.example.bts.bTS.impl.KIOSKImpl <em>KIOSK</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bts.bTS.impl.KIOSKImpl
     * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getKIOSK()
     * @generated
     */
    EClass KIOSK = eINSTANCE.getKIOSK();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KIOSK__SUPER_TYPE = eINSTANCE.getKIOSK_SuperType();

    /**
     * The meta object literal for the '{@link org.xtext.example.bts.bTS.impl.BusImpl <em>Bus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bts.bTS.impl.BusImpl
     * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getBus()
     * @generated
     */
    EClass BUS = eINSTANCE.getBus();

    /**
     * The meta object literal for the '{@link org.xtext.example.bts.bTS.impl.CityImpl <em>City</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bts.bTS.impl.CityImpl
     * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getCity()
     * @generated
     */
    EClass CITY = eINSTANCE.getCity();

    /**
     * The meta object literal for the '<em><b>Busstops</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CITY__BUSSTOPS = eINSTANCE.getCity_Busstops();

    /**
     * The meta object literal for the '{@link org.xtext.example.bts.bTS.impl.SeatImpl <em>Seat</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bts.bTS.impl.SeatImpl
     * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getSeat()
     * @generated
     */
    EClass SEAT = eINSTANCE.getSeat();

    /**
     * The meta object literal for the '{@link org.xtext.example.bts.bTS.Point <em>Point</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bts.bTS.Point
     * @see org.xtext.example.bts.bTS.impl.BTSPackageImpl#getPoint()
     * @generated
     */
    EEnum POINT = eINSTANCE.getPoint();

  }

} //BTSPackage
