/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts.bTS;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>KIOSK</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bts.bTS.KIOSK#getSuperType <em>Super Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bts.bTS.BTSPackage#getKIOSK()
 * @model
 * @generated
 */
public interface KIOSK extends Type
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(Payment)
   * @see org.xtext.example.bts.bTS.BTSPackage#getKIOSK_SuperType()
   * @model
   * @generated
   */
  Payment getSuperType();

  /**
   * Sets the value of the '{@link org.xtext.example.bts.bTS.KIOSK#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(Payment value);

} // KIOSK
