/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts.bTS;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Point</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.bts.bTS.BTSPackage#getPoint()
 * @model
 * @generated
 */
public enum Point implements Enumerator
{
  /**
   * The '<em><b>ARRIVAL POINT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ARRIVAL_POINT_VALUE
   * @generated
   * @ordered
   */
  ARRIVAL_POINT(0, "ARRIVAL_POINT", "ARRIVAL_POINT"),

  /**
   * The '<em><b>DEPARTURE POINT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DEPARTURE_POINT_VALUE
   * @generated
   * @ordered
   */
  DEPARTURE_POINT(1, "DEPARTURE_POINT", "DEPARTURE_POINT");

  /**
   * The '<em><b>ARRIVAL POINT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ARRIVAL_POINT
   * @model
   * @generated
   * @ordered
   */
  public static final int ARRIVAL_POINT_VALUE = 0;

  /**
   * The '<em><b>DEPARTURE POINT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DEPARTURE_POINT
   * @model
   * @generated
   * @ordered
   */
  public static final int DEPARTURE_POINT_VALUE = 1;

  /**
   * An array of all the '<em><b>Point</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Point[] VALUES_ARRAY =
    new Point[]
    {
      ARRIVAL_POINT,
      DEPARTURE_POINT,
    };

  /**
   * A public read-only list of all the '<em><b>Point</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Point> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Point</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Point get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Point result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Point</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Point getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Point result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Point</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Point get(int value)
  {
    switch (value)
    {
      case ARRIVAL_POINT_VALUE: return ARRIVAL_POINT;
      case DEPARTURE_POINT_VALUE: return DEPARTURE_POINT;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Point(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Point
