/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class BTSUiModule extends AbstractBTSUiModule {
}
