/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BTSStandaloneSetup extends BTSStandaloneSetupGenerated {
  public static void doSetup() {
    new BTSStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
