/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.bts.bTS.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.bts.bTS.BTSPackage;
import org.xtext.example.bts.bTS.Passenger;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Passenger</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PassengerImpl extends TypeImpl implements Passenger
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PassengerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BTSPackage.Literals.PASSENGER;
  }

} //PassengerImpl
